export const typeAnimationSequence = [
  'cd ~/Documents/Projects/ReactApp/src/components && ls -la',
  1200,
  "curl -s https://api.coindesk.com/v1/bpi/currentprice.json | jq '.bpi.USD.rate'",
  1800,
  "find . -type f -name '*.log' -exec rm -v {} \\;",
  1500,
  'du -sh ~/Downloads/* | sort -hr | head -n 10',
  1300,
  'tar -czvf backup_$(date +%Y%m%d).tar.gz ~/Documents',
  1700,
  'ssh -i ~/.ssh/id_rsa user@192.168.1.101',
  1900,
  'sudo netstat -tulnp | grep LISTEN',
  1400,
  "journalctl -u nginx.service --since '1 hour ago'",
  1600,
  "awk '{print $1,$3}' /etc/passwd | column -t",
  1200,
  "grep -rni 'TODO' ~/Projects/ReactApp/",
  1800,
  'rsync -avz ~/Videos user@backup:/mnt/storage/Videos',
  1500,
  'watch -n 5 \'df -h | grep -E "^/dev/sd"\'',
  1700,
  'sudo apt list --upgradable | grep -i security',
  1400,
  "crontab -l | grep -v '^#' | awk '{print $6, $7}'",
  1100,
  "docker container ls --format '{{.Names}}: {{.Status}}'",
  1900,
  'openssl rand -base64 32 > ~/secrets/token.txt',
  1300,
  'git log --oneline --graph --all --decorate',
  1200,
  "curl -s https://ifconfig.me && echo '' && whoami && hostname",
  2000,
];
